In [1]:
%run ../utils.ipynb

In [2]:
M1 = M_(2925, 5, 'г')
L = M_(220, 0.5, 'см')

d = M_(130, 0.5, 'см')
r = M_(22, 0.2, 'см')
R = M_(33, 0.2, 'см')
M2 = M_(727.2, 0.5, 'г')

g = M_(9.81, 0.01, 'м/с^2')

In [3]:
df = pd.read_excel("data.ods", engine="odf", sheet_name=None)
df

{'1':      m
 0  502
 1  508
 2  508
 3  487
 4  504
 5  507
 6  516
 7  507
 8  509
 9  499,
 '2':       dx
 0  12.20
 1  12.10
 2  12.00
 3  12.10
 4  12.05,
 '3':     N      t    A
 0  10  52.50  6.1
 1  10  69.11  4.5
 2  10  69.03  4.8
 3  10  68.71  4.7
 4  10  68.86  4.4}

In [4]:
m1 = M_(df["1"].to_numpy(), 0.1, 'мг')
dx = M_(df["2"].to_numpy(), 0.5, 'мм')
u1 = (1/m1[:5]*M1*(g/L)**0.5*dx).to('м/с')
u1mean = pint.Measurement(u1.mean())
u1

array([150.108452321018+/-6.16024466841471,
       147.11965294441842+/-6.087351059729586,
       145.90378804405134+/-6.087219023249633,
       153.46362155187796+/-6.349850968287228,
       147.67451192672883+/-6.135597787268218], dtype=object) <Unit('м / с')>

In [13]:
T = M_(df["3"]["t"], 0.02, 'с') / df["3"]["N"].to_numpy()
A = M_(df["3"]["A"], 0.05, 'см')
phi = A / d
T1 = T[1:].mean() # TODO: add std
T2 = T[0]
sqrtkI = (4 * np.pi * M2 * R**2 * T1 / (T1**2-T2**2)).to("кг м^2/с")
u2 = (phi[1:] * sqrtkI / r / m1[6:]).to("м/с")
u2mean = pint.Measurement(u2.mean())
u2, u2mean
# sqrtkI.to("кг м^2/с")

(array([104.8557836642654+/-2.0162184379651,
        113.83160419883956+/-2.1441062605525727,
        111.02215522487512+/-2.10489479727714,
        106.01851312907957+/-2.0541696073350124], dtype=object) <Unit('м / с')>,
 <Measurement(108.93201405426491, 1.8090497240749357, м / с)>)

In [6]:
table1 = pd.DataFrame({
    'Nb': range(1,11),
    'm': df["1"]["m"],
    # 't': df["3"]["t"],
    # 'dx': unp.nominal_values(A.m),
    # 'phi':  unp.nominal_values(phi.m),
    # 'u1': unp.nominal_values(u1.m)
}).to_numpy()
table1

array([[  1, 502],
       [  2, 508],
       [  3, 508],
       [  4, 487],
       [  5, 504],
       [  6, 507],
       [  7, 516],
       [  8, 507],
       [  9, 509],
       [ 10, 499]])

In [7]:
table2 = pd.DataFrame({
    'Nb': range(1,6),
    'dx': df["2"]["dx"],
    # 't': df["3"]["t"],
    # 'dx': unp.nominal_values(A.m),
    # 'phi':  unp.nominal_values(phi.m),
    'u1': u1.m
}).to_numpy()
table2

array([[1, 12.2, 150.108452321018+/-6.16024466841471],
       [2, 12.1, 147.11965294441842+/-6.087351059729586],
       [3, 12.0, 145.90378804405134+/-6.087219023249633],
       [4, 12.1, 153.46362155187796+/-6.349850968287228],
       [5, 12.05, 147.67451192672883+/-6.135597787268218]], dtype=object)

In [8]:
table3 = pd.DataFrame({
    'Nb': range(6,11),
    'N': [10]*5,
    't': df["3"]["t"],
    'T': unp.nominal_values(T.m),
    'dx': unp.nominal_values(A.m),
    'phi':  unp.nominal_values(phi.m),
    'u2': np.concatenate(([np.nan * u("м/с")], u2))
}).to_numpy()
table3

/nix/store/nrixknxpg35wdd9c4iw8x1b0jq53h6i5-python3-3.11.5-env/lib/python3.11/site-packages/pandas/core/construction.py:616: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.array(data, copy=copy)


array([[6, 10, 52.5, 5.25, 6.1, 0.04692307692307692, nan],
       [7, 10, 69.11, 6.911, 4.5, 0.03461538461538462,
        104.8557836642654+/-2.0162184379651],
       [8, 10, 69.03, 6.9030000000000005, 4.8, 0.03692307692307692,
        113.83160419883956+/-2.1441062605525727],
       [9, 10, 68.71, 6.8709999999999996, 4.7, 0.036153846153846154,
        111.02215522487512+/-2.10489479727714],
       [10, 10, 68.86, 6.886, 4.4, 0.03384615384615385,
        106.01851312907957+/-2.0541696073350124]], dtype=object)

In [9]:
# T

In [10]:
# pd.DataFrame()

In [11]:
# pint.Measurement(u1mean)

In [12]:
save()